language: haskell

env:
  - GHCVER=7.8.3
  - GHCVER=7.10.3
  - GHCVER=8.0.1
  - GHCVER=head

matrix:
  allow_failures:
   - env: GHCVER=head

before_install:
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install -y -qq cabal-install-1.20 ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.20/bin:$PATH
  - sudo apt-get install -qq libxxf86vm-dev
